### ISSUE TITLE
Disable CustomTypeConstructorArgs for empty tuples (unit)

### ISSUE THREAD

**Issue by kutyel** [jfmengels/elm-review#103]
**Describe the bug**
```
NoUnused.CustomTypeConstructorArgs: Argument is never extracted and therefore
never used.

226|     | LoggedInError (Result Decode.Error ErrorData)
227|     | DeleteChapter (Result Firestore.Error ())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
228|     | ReadChapter (Result Firestore.Error (Firestore.Document Reading))

This argument is never used. You should either use it somewhere, or remove it at
the location I pointed at.
```

**Expected behavior**
I don't think I should get a failing build when the actual type of the [delete](https://package.elm-lang.org/packages/IzumiSy/elm-firestore/latest/Firestore#delete) REST API firestore message is `delete : Path (DocumentPath a) -> Task Error ()`, maybe there is a way to disable this rule in my project? 🤔 

Thanks in advance!

**Comment by jfmengels** [comment]
If you never care about whether the operation failed or succeeded, then I would change your code to make that explicit, like this:

```elm
type Msg = ...
  | DeleteChapter

cmd =
  yourTask
    |> Task.attempt (\_ -> DeleteChapter)
```

You can do a similar thing to transform the Result into a boolean if you don't really use it.

I'll close the issue as this is the intended"workaround" (quotes because I think it makes the code better anyway), but feel free to reply if you disagree.

**Comment by kutyel** [comment]
Makes sense, thanks! I'll go with

```elm
|> Task.attempt (always DeleteChapter)
```

👍🏻
