### ISSUE TITLE
Can not run elm-review v2

### ISSUE THREAD

**Issue by ShrykeWindgrace** [jfmengels/elm-review#8]
Hi!

Thanks for your awesome work, I enjoyed the v1 version of `elm-review`, and now I'm trying to make v2 work.

Setup: elm-0.19.1, elm-review-2.0.0

```bash
$ npm i -g elm-review@2.0.0
$ mkdir tmp && cd tmp
$ elm init   # yes 
$ elm-review init   # yes
```
After that I run `elm-review` and face a wall of compilation errors, starting with
```
-- MODULE NOT FOUND ------------------------- elm-review-src\Elm\Review\Main.elm

You are trying to import a `Review.Fix` module:

13| import Review.Fix as Fix exposing (FixResult)
           ^^^^^^^^^^
I checked the "dependencies" and "source-directories" listed in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?

    Elm.Review.Main
    Elm.Review.Text
    Bitwise
    Elm.Error

Hint: If it is not a typo, check the "dependencies" and "source-directories" of
your elm.json to make sure all the packages you need are listed there!

-- MODULE NOT FOUND ------------------------- elm-review-src\Elm\Review\Main.elm

You are trying to import a `Review.Project` module:

14| import Review.Project as Project exposing (Project, ProjectModule)
           ^^^^^^^^^^^^^^
I checked the "dependencies" and "source-directories" listed in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?

    Elm.Review.Text
    Elm.Parser
    Elm.Writer
    Process
```
and so on.

Is there something off with my setup? If yes, what should I fix?

Cheers

**Comment by jfmengels** [comment]
Hello @ShrykeWindgrace :wave: 

I can't seem to reproduce your problem with the from scratch setup you provided. Do you by any chance have a project I could checkout locally?

I can reproduce the problem by removing the `jfmengels/elm-review` dependency from `review/elm.json` manually though, so I'm guessing that that is the problem.

`jfmengels/elm-review` gets added on `elm-review` but requires Internet access because "behind the scenes" it is adding dependencies through `elm install` (well, `elm-json install` to be more precise).

I suggest you look at what is in `review/elm.json` and check if this hypothesis is correct. Then I suggest running `elm-review init` again with Internet access and checking whether the dependencies were added correctly or not.

Let me know how this goes!

**Comment by ShrykeWindgrace** [comment]
@jfmengels indeed, for some unfathomable reason the dependency on `elm-review` landed in `indirect` section instead of `direct`. Moving it where it belongs fixed the issue. Yet my Internet connection seems ok, no hiccups on youtube.

Thanks a lot for your help!

**Comment by jfmengels** [comment]
Good to hear!
